### ISSUE TITLE
EOFException when *.index is empty

### ISSUE THREAD

**Issue by jetnet** [Norconex/jef#12]
Collector cannot start when its `*.index` file is empty (for whatever reason).
How to reproduce:
* start a collector and wait until it's done
* reset it's `index` file, e.g.:
```
> /var/norconex/output/progress/latest/localhost.index
```
* start it again:
```
INFO  [JobSuite] JEF work directory is: /var/norconex/output/progress
INFO  [JobSuite] JEF log manager is : FileLogManager
INFO  [JobSuite] JEF job status store is : FileJobStatusStore
INFO  [AbstractCollector] Suite of 1 crawler jobs created.
INFO  [JobSuite] Initialization...
FATAL [JobSuite] Job suite execution failed: localhost
java.io.EOFException
        at java.io.RandomAccessFile.readUnsignedShort(RandomAccessFile.java:745)
        at java.io.DataInputStream.readUTF(DataInputStream.java:589)
        at java.io.RandomAccessFile.readUTF(RandomAccessFile.java:965)
        at com.norconex.jef4.status.JobSuiteStatusSnapshot.newSnapshot(JobSuiteStatusSnapshot.java:177)
        at com.norconex.jef4.suite.JobSuite.initialize(JobSuite.java:457)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:274)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:165)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:150)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74)
```

Versions:
```
-rw-r--r--. 1 root root   195685 May 15 23:13 norconex-collector-core-1.9.2-SNAPSHOT.jar
-rw-r--r--. 1 root root    59815 Jan  5 18:36 norconex-committer-core-2.1.3-SNAPSHOT.jar
-rw-r--r--. 1 root root    93685 Apr 23 23:16 norconex-jef-4.1.2-SNAPSHOT.jar
```

**Comment by essiembre** [comment]
Please try the latest snapshot, which now logs an error instead of throwing an exception.
